version: '{build}'
clone_folder: C:\gopath\src\github.com\dougwatson\afero
environment:
  GOPATH: C:\gopath
build_script:
- cmd: >-
    go version

    go env

    go get -v github.com/dougwatson/afero/...

    go build -v github.com/dougwatson/afero/...
test_script:
- cmd: go test -count=1 -cover -race -v github.com/dougwatson/afero/...
